// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OIDC_ArtifactServer.Models;

#nullable disable

namespace OIDC_ArtifactServer.Migrations
{
    [DbContext(typeof(ArtifactDb))]
    [Migration("20220707201206_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OIDC_ArtifactServer.Models.AccessToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AccessTokens");
                });

            modelBuilder.Entity("OIDC_ArtifactServer.Models.ArtifactBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ArtifactBranch");
                });

            modelBuilder.Entity("OIDC_ArtifactServer.Models.ArtifactEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArtifactBranchId")
                        .HasColumnType("integer");

                    b.Property<string>("EntryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeAdded")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactBranchId");

                    b.ToTable("ArtifactEntry");
                });

            modelBuilder.Entity("OIDC_ArtifactServer.Models.ArtifactFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArtifactEntryId")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactEntryId");

                    b.ToTable("ArtifactFile");
                });

            modelBuilder.Entity("OIDC_ArtifactServer.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("OIDC_ArtifactServer.Models.ArtifactBranch", b =>
                {
                    b.HasOne("OIDC_ArtifactServer.Models.Project", null)
                        .WithMany("Branches")
                        .HasForeignKey("ProjectId");
                });

            modelBuilder.Entity("OIDC_ArtifactServer.Models.ArtifactEntry", b =>
                {
                    b.HasOne("OIDC_ArtifactServer.Models.ArtifactBranch", null)
                        .WithMany("Artifacts")
                        .HasForeignKey("ArtifactBranchId");
                });

            modelBuilder.Entity("OIDC_ArtifactServer.Models.ArtifactFile", b =>
                {
                    b.HasOne("OIDC_ArtifactServer.Models.ArtifactEntry", null)
                        .WithMany("Files")
                        .HasForeignKey("ArtifactEntryId");
                });

            modelBuilder.Entity("OIDC_ArtifactServer.Models.ArtifactBranch", b =>
                {
                    b.Navigation("Artifacts");
                });

            modelBuilder.Entity("OIDC_ArtifactServer.Models.ArtifactEntry", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("OIDC_ArtifactServer.Models.Project", b =>
                {
                    b.Navigation("Branches");
                });
#pragma warning restore 612, 618
        }
    }
}
